// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.github.nowelium.phpbuf;

public final class ExampleSearch {
  private ExampleSearch() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Web extends
      com.google.protobuf.GeneratedMessage {
    // Use Web.newBuilder() to construct.
    private Web() {}
    
    private static final Web defaultInstance = new Web();
    public static Web getDefaultInstance() {
      return defaultInstance;
    }
    
    public Web getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.nowelium.phpbuf.ExampleSearch.internal_static_com_github_nowelium_phpbuf_Web_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.nowelium.phpbuf.ExampleSearch.internal_static_com_github_nowelium_phpbuf_Web_fieldAccessorTable;
    }
    
    public enum SiteType
        implements com.google.protobuf.ProtocolMessageEnum {
      BLOG(0, 0),
      NEWS(1, 1),
      VIDEO(2, 2),
      UNKNOWN(3, 3),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static SiteType valueOf(int value) {
        switch (value) {
          case 0: return BLOG;
          case 1: return NEWS;
          case 2: return VIDEO;
          case 3: return UNKNOWN;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<SiteType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<SiteType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SiteType>() {
              public SiteType findValueByNumber(int number) {
                return SiteType.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.github.nowelium.phpbuf.ExampleSearch.Web.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final SiteType[] VALUES = {
        BLOG, NEWS, VIDEO, UNKNOWN, 
      };
      public static SiteType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private SiteType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        com.github.nowelium.phpbuf.ExampleSearch.getDescriptor();
      }
    }
    
    public static final class Site extends
        com.google.protobuf.GeneratedMessage {
      // Use Site.newBuilder() to construct.
      private Site() {}
      
      private static final Site defaultInstance = new Site();
      public static Site getDefaultInstance() {
        return defaultInstance;
      }
      
      public Site getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.nowelium.phpbuf.ExampleSearch.internal_static_com_github_nowelium_phpbuf_Web_Site_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.nowelium.phpbuf.ExampleSearch.internal_static_com_github_nowelium_phpbuf_Web_Site_fieldAccessorTable;
      }
      
      // required string url = 1;
      public static final int URL_FIELD_NUMBER = 1;
      private boolean hasUrl;
      private java.lang.String url_ = "";
      public boolean hasUrl() { return hasUrl; }
      public java.lang.String getUrl() { return url_; }
      
      // required string title = 2;
      public static final int TITLE_FIELD_NUMBER = 2;
      private boolean hasTitle;
      private java.lang.String title_ = "";
      public boolean hasTitle() { return hasTitle; }
      public java.lang.String getTitle() { return title_; }
      
      // required .com.github.nowelium.phpbuf.Web.SiteType type = 3;
      public static final int TYPE_FIELD_NUMBER = 3;
      private boolean hasType;
      private com.github.nowelium.phpbuf.ExampleSearch.Web.SiteType type_ = com.github.nowelium.phpbuf.ExampleSearch.Web.SiteType.BLOG;
      public boolean hasType() { return hasType; }
      public com.github.nowelium.phpbuf.ExampleSearch.Web.SiteType getType() { return type_; }
      
      // optional string summary = 4;
      public static final int SUMMARY_FIELD_NUMBER = 4;
      private boolean hasSummary;
      private java.lang.String summary_ = "";
      public boolean hasSummary() { return hasSummary; }
      public java.lang.String getSummary() { return summary_; }
      
      public final boolean isInitialized() {
        if (!hasUrl) return false;
        if (!hasTitle) return false;
        if (!hasType) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasUrl()) {
          output.writeString(1, getUrl());
        }
        if (hasTitle()) {
          output.writeString(2, getTitle());
        }
        if (hasType()) {
          output.writeEnum(3, getType().getNumber());
        }
        if (hasSummary()) {
          output.writeString(4, getSummary());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasUrl()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getUrl());
        }
        if (hasTitle()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getTitle());
        }
        if (hasType()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(3, getType().getNumber());
        }
        if (hasSummary()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(4, getSummary());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static com.github.nowelium.phpbuf.ExampleSearch.Web.Site parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Web.Site parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Web.Site parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Web.Site parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Web.Site parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Web.Site parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Web.Site parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Web.Site parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Web.Site parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Web.Site parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.github.nowelium.phpbuf.ExampleSearch.Web.Site prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private com.github.nowelium.phpbuf.ExampleSearch.Web.Site result;
        
        // Construct using com.github.nowelium.phpbuf.ExampleSearch.Web.Site.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new com.github.nowelium.phpbuf.ExampleSearch.Web.Site();
          return builder;
        }
        
        protected com.github.nowelium.phpbuf.ExampleSearch.Web.Site internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new com.github.nowelium.phpbuf.ExampleSearch.Web.Site();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.github.nowelium.phpbuf.ExampleSearch.Web.Site.getDescriptor();
        }
        
        public com.github.nowelium.phpbuf.ExampleSearch.Web.Site getDefaultInstanceForType() {
          return com.github.nowelium.phpbuf.ExampleSearch.Web.Site.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public com.github.nowelium.phpbuf.ExampleSearch.Web.Site build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private com.github.nowelium.phpbuf.ExampleSearch.Web.Site buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public com.github.nowelium.phpbuf.ExampleSearch.Web.Site buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          com.github.nowelium.phpbuf.ExampleSearch.Web.Site returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.github.nowelium.phpbuf.ExampleSearch.Web.Site) {
            return mergeFrom((com.github.nowelium.phpbuf.ExampleSearch.Web.Site)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.github.nowelium.phpbuf.ExampleSearch.Web.Site other) {
          if (other == com.github.nowelium.phpbuf.ExampleSearch.Web.Site.getDefaultInstance()) return this;
          if (other.hasUrl()) {
            setUrl(other.getUrl());
          }
          if (other.hasTitle()) {
            setTitle(other.getTitle());
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasSummary()) {
            setSummary(other.getSummary());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setUrl(input.readString());
                break;
              }
              case 18: {
                setTitle(input.readString());
                break;
              }
              case 24: {
                int rawValue = input.readEnum();
                com.github.nowelium.phpbuf.ExampleSearch.Web.SiteType value = com.github.nowelium.phpbuf.ExampleSearch.Web.SiteType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(3, rawValue);
                } else {
                  setType(value);
                }
                break;
              }
              case 34: {
                setSummary(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required string url = 1;
        public boolean hasUrl() {
          return result.hasUrl();
        }
        public java.lang.String getUrl() {
          return result.getUrl();
        }
        public Builder setUrl(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasUrl = true;
          result.url_ = value;
          return this;
        }
        public Builder clearUrl() {
          result.hasUrl = false;
          result.url_ = getDefaultInstance().getUrl();
          return this;
        }
        
        // required string title = 2;
        public boolean hasTitle() {
          return result.hasTitle();
        }
        public java.lang.String getTitle() {
          return result.getTitle();
        }
        public Builder setTitle(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasTitle = true;
          result.title_ = value;
          return this;
        }
        public Builder clearTitle() {
          result.hasTitle = false;
          result.title_ = getDefaultInstance().getTitle();
          return this;
        }
        
        // required .com.github.nowelium.phpbuf.Web.SiteType type = 3;
        public boolean hasType() {
          return result.hasType();
        }
        public com.github.nowelium.phpbuf.ExampleSearch.Web.SiteType getType() {
          return result.getType();
        }
        public Builder setType(com.github.nowelium.phpbuf.ExampleSearch.Web.SiteType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          result.hasType = true;
          result.type_ = value;
          return this;
        }
        public Builder clearType() {
          result.hasType = false;
          result.type_ = com.github.nowelium.phpbuf.ExampleSearch.Web.SiteType.BLOG;
          return this;
        }
        
        // optional string summary = 4;
        public boolean hasSummary() {
          return result.hasSummary();
        }
        public java.lang.String getSummary() {
          return result.getSummary();
        }
        public Builder setSummary(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasSummary = true;
          result.summary_ = value;
          return this;
        }
        public Builder clearSummary() {
          result.hasSummary = false;
          result.summary_ = getDefaultInstance().getSummary();
          return this;
        }
      }
      
      static {
        com.github.nowelium.phpbuf.ExampleSearch.getDescriptor();
      }
      
      static {
        com.github.nowelium.phpbuf.ExampleSearch.internalForceInit();
      }
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.github.nowelium.phpbuf.ExampleSearch.Web parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Web parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Web parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Web parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Web parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Web parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Web parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Web parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Web parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Web parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.nowelium.phpbuf.ExampleSearch.Web prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.github.nowelium.phpbuf.ExampleSearch.Web result;
      
      // Construct using com.github.nowelium.phpbuf.ExampleSearch.Web.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.github.nowelium.phpbuf.ExampleSearch.Web();
        return builder;
      }
      
      protected com.github.nowelium.phpbuf.ExampleSearch.Web internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.github.nowelium.phpbuf.ExampleSearch.Web();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.nowelium.phpbuf.ExampleSearch.Web.getDescriptor();
      }
      
      public com.github.nowelium.phpbuf.ExampleSearch.Web getDefaultInstanceForType() {
        return com.github.nowelium.phpbuf.ExampleSearch.Web.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.github.nowelium.phpbuf.ExampleSearch.Web build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.github.nowelium.phpbuf.ExampleSearch.Web buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.github.nowelium.phpbuf.ExampleSearch.Web buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.github.nowelium.phpbuf.ExampleSearch.Web returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.nowelium.phpbuf.ExampleSearch.Web) {
          return mergeFrom((com.github.nowelium.phpbuf.ExampleSearch.Web)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.github.nowelium.phpbuf.ExampleSearch.Web other) {
        if (other == com.github.nowelium.phpbuf.ExampleSearch.Web.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
    }
    
    static {
      com.github.nowelium.phpbuf.ExampleSearch.getDescriptor();
    }
    
    static {
      com.github.nowelium.phpbuf.ExampleSearch.internalForceInit();
    }
  }
  
  public static final class Request extends
      com.google.protobuf.GeneratedMessage {
    // Use Request.newBuilder() to construct.
    private Request() {}
    
    private static final Request defaultInstance = new Request();
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.nowelium.phpbuf.ExampleSearch.internal_static_com_github_nowelium_phpbuf_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.nowelium.phpbuf.ExampleSearch.internal_static_com_github_nowelium_phpbuf_Request_fieldAccessorTable;
    }
    
    public static final class SearchRequest extends
        com.google.protobuf.GeneratedMessage {
      // Use SearchRequest.newBuilder() to construct.
      private SearchRequest() {}
      
      private static final SearchRequest defaultInstance = new SearchRequest();
      public static SearchRequest getDefaultInstance() {
        return defaultInstance;
      }
      
      public SearchRequest getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.nowelium.phpbuf.ExampleSearch.internal_static_com_github_nowelium_phpbuf_Request_SearchRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.nowelium.phpbuf.ExampleSearch.internal_static_com_github_nowelium_phpbuf_Request_SearchRequest_fieldAccessorTable;
      }
      
      // required string query = 1;
      public static final int QUERY_FIELD_NUMBER = 1;
      private boolean hasQuery;
      private java.lang.String query_ = "";
      public boolean hasQuery() { return hasQuery; }
      public java.lang.String getQuery() { return query_; }
      
      public final boolean isInitialized() {
        if (!hasQuery) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasQuery()) {
          output.writeString(1, getQuery());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasQuery()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getQuery());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest result;
        
        // Construct using com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest();
          return builder;
        }
        
        protected com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest.getDescriptor();
        }
        
        public com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest getDefaultInstanceForType() {
          return com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest) {
            return mergeFrom((com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest other) {
          if (other == com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest.getDefaultInstance()) return this;
          if (other.hasQuery()) {
            setQuery(other.getQuery());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setQuery(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required string query = 1;
        public boolean hasQuery() {
          return result.hasQuery();
        }
        public java.lang.String getQuery() {
          return result.getQuery();
        }
        public Builder setQuery(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasQuery = true;
          result.query_ = value;
          return this;
        }
        public Builder clearQuery() {
          result.hasQuery = false;
          result.query_ = getDefaultInstance().getQuery();
          return this;
        }
      }
      
      static {
        com.github.nowelium.phpbuf.ExampleSearch.getDescriptor();
      }
      
      static {
        com.github.nowelium.phpbuf.ExampleSearch.internalForceInit();
      }
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.github.nowelium.phpbuf.ExampleSearch.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.nowelium.phpbuf.ExampleSearch.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.github.nowelium.phpbuf.ExampleSearch.Request result;
      
      // Construct using com.github.nowelium.phpbuf.ExampleSearch.Request.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.github.nowelium.phpbuf.ExampleSearch.Request();
        return builder;
      }
      
      protected com.github.nowelium.phpbuf.ExampleSearch.Request internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.github.nowelium.phpbuf.ExampleSearch.Request();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.nowelium.phpbuf.ExampleSearch.Request.getDescriptor();
      }
      
      public com.github.nowelium.phpbuf.ExampleSearch.Request getDefaultInstanceForType() {
        return com.github.nowelium.phpbuf.ExampleSearch.Request.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.github.nowelium.phpbuf.ExampleSearch.Request build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.github.nowelium.phpbuf.ExampleSearch.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.github.nowelium.phpbuf.ExampleSearch.Request buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.github.nowelium.phpbuf.ExampleSearch.Request returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.nowelium.phpbuf.ExampleSearch.Request) {
          return mergeFrom((com.github.nowelium.phpbuf.ExampleSearch.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.github.nowelium.phpbuf.ExampleSearch.Request other) {
        if (other == com.github.nowelium.phpbuf.ExampleSearch.Request.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
    }
    
    static {
      com.github.nowelium.phpbuf.ExampleSearch.getDescriptor();
    }
    
    static {
      com.github.nowelium.phpbuf.ExampleSearch.internalForceInit();
    }
  }
  
  public static final class Response extends
      com.google.protobuf.GeneratedMessage {
    // Use Response.newBuilder() to construct.
    private Response() {}
    
    private static final Response defaultInstance = new Response();
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.nowelium.phpbuf.ExampleSearch.internal_static_com_github_nowelium_phpbuf_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.nowelium.phpbuf.ExampleSearch.internal_static_com_github_nowelium_phpbuf_Response_fieldAccessorTable;
    }
    
    public static final class SearchResult extends
        com.google.protobuf.GeneratedMessage {
      // Use SearchResult.newBuilder() to construct.
      private SearchResult() {}
      
      private static final SearchResult defaultInstance = new SearchResult();
      public static SearchResult getDefaultInstance() {
        return defaultInstance;
      }
      
      public SearchResult getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.nowelium.phpbuf.ExampleSearch.internal_static_com_github_nowelium_phpbuf_Response_SearchResult_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.nowelium.phpbuf.ExampleSearch.internal_static_com_github_nowelium_phpbuf_Response_SearchResult_fieldAccessorTable;
      }
      
      // repeated .com.github.nowelium.phpbuf.Web.Site sites = 1;
      public static final int SITES_FIELD_NUMBER = 1;
      private java.util.List<com.github.nowelium.phpbuf.ExampleSearch.Web.Site> sites_ =
        java.util.Collections.emptyList();
      public java.util.List<com.github.nowelium.phpbuf.ExampleSearch.Web.Site> getSitesList() {
        return sites_;
      }
      public int getSitesCount() { return sites_.size(); }
      public com.github.nowelium.phpbuf.ExampleSearch.Web.Site getSites(int index) {
        return sites_.get(index);
      }
      
      public final boolean isInitialized() {
        for (com.github.nowelium.phpbuf.ExampleSearch.Web.Site element : getSitesList()) {
          if (!element.isInitialized()) return false;
        }
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (com.github.nowelium.phpbuf.ExampleSearch.Web.Site element : getSitesList()) {
          output.writeMessage(1, element);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        for (com.github.nowelium.phpbuf.ExampleSearch.Web.Site element : getSitesList()) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, element);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult result;
        
        // Construct using com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult();
          return builder;
        }
        
        protected com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult.getDescriptor();
        }
        
        public com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult getDefaultInstanceForType() {
          return com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          if (result.sites_ != java.util.Collections.EMPTY_LIST) {
            result.sites_ =
              java.util.Collections.unmodifiableList(result.sites_);
          }
          com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult) {
            return mergeFrom((com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult other) {
          if (other == com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult.getDefaultInstance()) return this;
          if (!other.sites_.isEmpty()) {
            if (result.sites_.isEmpty()) {
              result.sites_ = new java.util.ArrayList<com.github.nowelium.phpbuf.ExampleSearch.Web.Site>();
            }
            result.sites_.addAll(other.sites_);
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                com.github.nowelium.phpbuf.ExampleSearch.Web.Site.Builder subBuilder = com.github.nowelium.phpbuf.ExampleSearch.Web.Site.newBuilder();
                input.readMessage(subBuilder, extensionRegistry);
                addSites(subBuilder.buildPartial());
                break;
              }
            }
          }
        }
        
        
        // repeated .com.github.nowelium.phpbuf.Web.Site sites = 1;
        public java.util.List<com.github.nowelium.phpbuf.ExampleSearch.Web.Site> getSitesList() {
          return java.util.Collections.unmodifiableList(result.sites_);
        }
        public int getSitesCount() {
          return result.getSitesCount();
        }
        public com.github.nowelium.phpbuf.ExampleSearch.Web.Site getSites(int index) {
          return result.getSites(index);
        }
        public Builder setSites(int index, com.github.nowelium.phpbuf.ExampleSearch.Web.Site value) {
          if (value == null) {
            throw new NullPointerException();
          }
          result.sites_.set(index, value);
          return this;
        }
        public Builder setSites(int index, com.github.nowelium.phpbuf.ExampleSearch.Web.Site.Builder builderForValue) {
          result.sites_.set(index, builderForValue.build());
          return this;
        }
        public Builder addSites(com.github.nowelium.phpbuf.ExampleSearch.Web.Site value) {
          if (value == null) {
            throw new NullPointerException();
          }
          if (result.sites_.isEmpty()) {
            result.sites_ = new java.util.ArrayList<com.github.nowelium.phpbuf.ExampleSearch.Web.Site>();
          }
          result.sites_.add(value);
          return this;
        }
        public Builder addSites(com.github.nowelium.phpbuf.ExampleSearch.Web.Site.Builder builderForValue) {
          if (result.sites_.isEmpty()) {
            result.sites_ = new java.util.ArrayList<com.github.nowelium.phpbuf.ExampleSearch.Web.Site>();
          }
          result.sites_.add(builderForValue.build());
          return this;
        }
        public Builder addAllSites(
            java.lang.Iterable<? extends com.github.nowelium.phpbuf.ExampleSearch.Web.Site> values) {
          if (result.sites_.isEmpty()) {
            result.sites_ = new java.util.ArrayList<com.github.nowelium.phpbuf.ExampleSearch.Web.Site>();
          }
          super.addAll(values, result.sites_);
          return this;
        }
        public Builder clearSites() {
          result.sites_ = java.util.Collections.emptyList();
          return this;
        }
      }
      
      static {
        com.github.nowelium.phpbuf.ExampleSearch.getDescriptor();
      }
      
      static {
        com.github.nowelium.phpbuf.ExampleSearch.internalForceInit();
      }
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.github.nowelium.phpbuf.ExampleSearch.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.nowelium.phpbuf.ExampleSearch.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.nowelium.phpbuf.ExampleSearch.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.github.nowelium.phpbuf.ExampleSearch.Response result;
      
      // Construct using com.github.nowelium.phpbuf.ExampleSearch.Response.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.github.nowelium.phpbuf.ExampleSearch.Response();
        return builder;
      }
      
      protected com.github.nowelium.phpbuf.ExampleSearch.Response internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.github.nowelium.phpbuf.ExampleSearch.Response();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.nowelium.phpbuf.ExampleSearch.Response.getDescriptor();
      }
      
      public com.github.nowelium.phpbuf.ExampleSearch.Response getDefaultInstanceForType() {
        return com.github.nowelium.phpbuf.ExampleSearch.Response.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.github.nowelium.phpbuf.ExampleSearch.Response build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.github.nowelium.phpbuf.ExampleSearch.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.github.nowelium.phpbuf.ExampleSearch.Response buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.github.nowelium.phpbuf.ExampleSearch.Response returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.nowelium.phpbuf.ExampleSearch.Response) {
          return mergeFrom((com.github.nowelium.phpbuf.ExampleSearch.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.github.nowelium.phpbuf.ExampleSearch.Response other) {
        if (other == com.github.nowelium.phpbuf.ExampleSearch.Response.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
    }
    
    static {
      com.github.nowelium.phpbuf.ExampleSearch.getDescriptor();
    }
    
    static {
      com.github.nowelium.phpbuf.ExampleSearch.internalForceInit();
    }
  }
  
  public static abstract class SearchService
      implements com.google.protobuf.Service {
    protected SearchService() {}
    
    public interface Interface {
      public abstract void search(
          com.google.protobuf.RpcController controller,
          com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest request,
          com.google.protobuf.RpcCallback<com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new SearchService() {
        @Override
        public  void search(
            com.google.protobuf.RpcController controller,
            com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest request,
            com.google.protobuf.RpcCallback<com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult> done) {
          impl.search(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.search(controller, (com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void search(
        com.google.protobuf.RpcController controller,
        com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest request,
        com.google.protobuf.RpcCallback<com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.github.nowelium.phpbuf.ExampleSearch.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.search(controller, (com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest)request,
            com.google.protobuf.RpcUtil.<com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends com.github.nowelium.phpbuf.ExampleSearch.SearchService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void search(
          com.google.protobuf.RpcController controller,
          com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest request,
          com.google.protobuf.RpcCallback<com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult.class,
            com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult search(
          com.google.protobuf.RpcController controller,
          com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult search(
          com.google.protobuf.RpcController controller,
          com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_nowelium_phpbuf_Web_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_nowelium_phpbuf_Web_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_nowelium_phpbuf_Web_Site_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_nowelium_phpbuf_Web_Site_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_nowelium_phpbuf_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_nowelium_phpbuf_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_nowelium_phpbuf_Request_SearchRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_nowelium_phpbuf_Request_SearchRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_nowelium_phpbuf_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_nowelium_phpbuf_Response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_nowelium_phpbuf_Response_SearchResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_nowelium_phpbuf_Response_SearchResult_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ExampleSearch.proto\022\032com.github.noweli" +
      "um.phpbuf\"\252\001\n\003Web\032k\n\004Site\022\013\n\003url\030\001 \002(\t\022\r" +
      "\n\005title\030\002 \002(\t\0226\n\004type\030\003 \002(\0162(.com.github" +
      ".nowelium.phpbuf.Web.SiteType\022\017\n\007summary" +
      "\030\004 \001(\t\"6\n\010SiteType\022\010\n\004BLOG\020\000\022\010\n\004NEWS\020\001\022\t" +
      "\n\005VIDEO\020\002\022\013\n\007UNKNOWN\020\003\")\n\007Request\032\036\n\rSea" +
      "rchRequest\022\r\n\005query\030\001 \002(\t\"O\n\010Response\032C\n" +
      "\014SearchResult\0223\n\005sites\030\001 \003(\0132$.com.githu" +
      "b.nowelium.phpbuf.Web.Site2\177\n\rSearchServ" +
      "ice\022n\n\006search\0221.com.github.nowelium.phpb",
      "uf.Request.SearchRequest\0321.com.github.no" +
      "welium.phpbuf.Response.SearchResultB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_github_nowelium_phpbuf_Web_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_github_nowelium_phpbuf_Web_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_github_nowelium_phpbuf_Web_descriptor,
              new java.lang.String[] { },
              com.github.nowelium.phpbuf.ExampleSearch.Web.class,
              com.github.nowelium.phpbuf.ExampleSearch.Web.Builder.class);
          internal_static_com_github_nowelium_phpbuf_Web_Site_descriptor =
            internal_static_com_github_nowelium_phpbuf_Web_descriptor.getNestedTypes().get(0);
          internal_static_com_github_nowelium_phpbuf_Web_Site_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_github_nowelium_phpbuf_Web_Site_descriptor,
              new java.lang.String[] { "Url", "Title", "Type", "Summary", },
              com.github.nowelium.phpbuf.ExampleSearch.Web.Site.class,
              com.github.nowelium.phpbuf.ExampleSearch.Web.Site.Builder.class);
          internal_static_com_github_nowelium_phpbuf_Request_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_github_nowelium_phpbuf_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_github_nowelium_phpbuf_Request_descriptor,
              new java.lang.String[] { },
              com.github.nowelium.phpbuf.ExampleSearch.Request.class,
              com.github.nowelium.phpbuf.ExampleSearch.Request.Builder.class);
          internal_static_com_github_nowelium_phpbuf_Request_SearchRequest_descriptor =
            internal_static_com_github_nowelium_phpbuf_Request_descriptor.getNestedTypes().get(0);
          internal_static_com_github_nowelium_phpbuf_Request_SearchRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_github_nowelium_phpbuf_Request_SearchRequest_descriptor,
              new java.lang.String[] { "Query", },
              com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest.class,
              com.github.nowelium.phpbuf.ExampleSearch.Request.SearchRequest.Builder.class);
          internal_static_com_github_nowelium_phpbuf_Response_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_github_nowelium_phpbuf_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_github_nowelium_phpbuf_Response_descriptor,
              new java.lang.String[] { },
              com.github.nowelium.phpbuf.ExampleSearch.Response.class,
              com.github.nowelium.phpbuf.ExampleSearch.Response.Builder.class);
          internal_static_com_github_nowelium_phpbuf_Response_SearchResult_descriptor =
            internal_static_com_github_nowelium_phpbuf_Response_descriptor.getNestedTypes().get(0);
          internal_static_com_github_nowelium_phpbuf_Response_SearchResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_github_nowelium_phpbuf_Response_SearchResult_descriptor,
              new java.lang.String[] { "Sites", },
              com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult.class,
              com.github.nowelium.phpbuf.ExampleSearch.Response.SearchResult.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
